In [2]:
import torch
from torch.autograd import Variable

In [12]:
x_tensor = torch.Tensor(3,4)
x_tensor

tensor([[-5.3776e+06,  3.0848e-41,  3.3631e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  4.4721e+21,  3.0104e+29],
        [ 7.1853e+22,  7.1901e+28,  6.2706e+22,  4.7428e+30]])

In [5]:
x_variable = Variable(x_tensor)
x_variable

tensor([[-5.3779e+06,  3.0848e-41,  5.0447e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3788e-14,  1.8369e+28],
        [ 1.9433e-19,  3.3738e-12,  7.4086e+28,  6.9397e+22]])

In [6]:
x_variable.data

tensor([[-5.3779e+06,  3.0848e-41,  5.0447e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3788e-14,  1.8369e+28],
        [ 1.9433e-19,  3.3738e-12,  7.4086e+28,  6.9397e+22]])

In [7]:
x_tensor.data

tensor([[-5.3779e+06,  3.0848e-41,  5.0447e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3788e-14,  1.8369e+28],
        [ 1.9433e-19,  3.3738e-12,  7.4086e+28,  6.9397e+22]])

In [16]:
print(x_tensor.grad)

None


In [20]:
x_tensor.requires_grad

False

In [21]:
x_tensor.requires_grad = True

In [27]:
x = Variable(torch.FloatTensor(3,4), requires_grad=True)
y = x**2 + 4*x
z = 2*y + 3

In [29]:
x.requires_grad, y.requires_grad, z.requires_grad

(True, True, True)

In [30]:
loss = torch.FloatTensor(3,4)
z.backward(loss)

print(x.grad)
y.grad, z.grad

tensor([[ 1.7819e+14,  2.4679e-40, -2.3589e-39,  1.2780e-42],
        [ 1.0874e-42,  1.1210e-42,         nan,         nan],
        [ 1.3677e-42,  4.2884e-21,  7.1679e-15,  1.1615e-11]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """


(None, None)