In [1]:
import torch
import torch.nn as nn
import torch.nn.init as init

In [3]:
img = torch.ones(1,1,3,3)
print(img)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [17]:
transpose1 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, 
                               stride=1, padding=0, output_padding=0, bias=False)

In [20]:
print(transpose1.weight.data)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [21]:
init.constant_(transpose1.weight.data, 1)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [22]:
transpose1(img)

tensor([[[[1., 2., 3., 2., 1.],
          [2., 4., 6., 4., 2.],
          [3., 6., 9., 6., 3.],
          [2., 4., 6., 4., 2.],
          [1., 2., 3., 2., 1.]]]], grad_fn=<SlowConvTranspose2DBackward>)

In [24]:
transpose2 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, 
                               stride=2, padding=0, output_padding=0, bias=False)
init.constant_(transpose2.weight.data, 1)
transpose2(img)

tensor([[[[1., 1., 2., 1., 2., 1., 1.],
          [1., 1., 2., 1., 2., 1., 1.],
          [2., 2., 4., 2., 4., 2., 2.],
          [1., 1., 2., 1., 2., 1., 1.],
          [2., 2., 4., 2., 4., 2., 2.],
          [1., 1., 2., 1., 2., 1., 1.],
          [1., 1., 2., 1., 2., 1., 1.]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

In [25]:
transpose3 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, 
                               stride=2, padding=1, output_padding=0, bias=False)
init.constant_(transpose3.weight.data, 1)
transpose3(img)

tensor([[[[1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.]]]], grad_fn=<SlowConvTranspose2DBackward>)

In [26]:
transpose4 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, 
                               stride=2, padding=0, output_padding=1, bias=False)
init.constant_(transpose4.weight.data, 1)
transpose4(img)

tensor([[[[1., 1., 2., 1., 2., 1., 1., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [2., 2., 4., 2., 4., 2., 2., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [2., 2., 4., 2., 4., 2., 2., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]],
       grad_fn=<SlowConvTranspose2DBackward>)

In [27]:
transpose5 = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, 
                               stride=2, padding=1, output_padding=1, bias=False)
# output_padding 먼저 갈기고, 그 다음 padding으로 후리는듯?
init.constant_(transpose5.weight.data, 1)
transpose5(img)

tensor([[[[1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [1., 2., 1., 2., 1., 1.]]]], grad_fn=<SlowConvTranspose2DBackward>)